### ISSUE TITLE
Failed to locate image

### ISSUE THREAD

**Issue by Klumbumbus** [Sowa1980/Start_Data_preset#1]
There is a missing icon or wrong icon path in each of your three github josm presets. Could you please fix them?
Failed to locate image 'Data32.svg'
Failed to locate image 'Rekvizit_32.svg'
Failed to locate image 'letter_box.png'

https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/

**Comment by Sowa1980** [comment]
Привет, что это обязательное правило наличие картинок и по чему Вы удаляете мои заготовки постоянно с этой страницы https://josm.openstreetmap.de/wiki/PresetsSource ? Они ни чем не хуже других заготовок, которые представлены как в .Zip формате файла так и в *.xml. Объясните свое поведение. Что конкретно Вам не нравится? все заготовки основаны на вики страницах OSM тегов.

**Comment by Klumbumbus** [comment]
This is not related to the osm tags (I didn't look at the tags in your presets). However Presets in the JOSM list at least need to be free of syntax errors. This will be tested automatically on https://josm.openstreetmap.de/jenkins/
In your presets the icon paths are wrong, thats why I disable them on PresetsSource.
Own icons need to be either the full URL path or relative to the zip file. So if you want to use a relative path a zip is required as the xml alone doesn't contain the icon.
In your zip there is a subfolder and then the icons. The icon paths in your xml are missing the subfolder.

**Comment by Sowa1980** [comment]
То есть если я Вас правильно понял, мне надо поместить все в Zip файл, а именно Start_Data.xml и значок Data32.png и указать верный путь в самом файле Start_Data.xml  до значка, или как вариант убрать вообще картинки значков и пути (ссылки на них) . И после опубликовать уже этот Zip файл .на странице https://josm.openstreetmap.de/jenkins/.  Верно я Вас понимаю?

**Comment by Klumbumbus** [comment]
> То есть если я Вас правильно понял, мне надо поместить все в Zip файл, а именно Start_Data.xml и значок Data32.png и указать верный путь в самом файле Start_Data.xml до значка.

Yes. After this is correct the Presets needs to be enabled on PresetsSource again.
You don't need to do anything on jenkins. Your preset will be automatically reported there if there is still an error, like right now: https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/testReport/

(Also please use svg icons instead of the png icons when available for better display on hi dpi screens.)

**Comment by Sowa1980** [comment]
Еще одна просьба не удалять заготовки сразу, а дать время на их доработку так, как локально на моем компьютере все пути и значки работают корректно. Если возможно давать хотя бы сутки что бы протестировать как загрузятся заготовки и значки с данной страницы.

**Comment by Klumbumbus** [comment]
Still all with errors. Can we please move the three presets to the JOSM wiki? This will end all the trouble.

**Comment by Sowa1980** [comment]
В чем проблема с картинками я не пойму, можете посмотреть скрин локально все работает верно, все картинки грузятся , скрины выложены в репозитории.
Нет я не умею делать вики страницы да и разбираться с ними не хочется, нет времени на это. Да и за чем, когда я тут работаю с гит хабом и планируется работа в команде.

**Comment by Klumbumbus** [comment]
> В чем проблема с картинками я не пойму, можете посмотреть скрин локально все работает верно, все картинки грузятся , скрины выложены в репозитории.

See my screenshot below. Probably on your computer it loads the icon from somewhere else but not from the zip.

> Да и за чем, когда я тут работаю с гит хабом и планируется работа в команде.

Because sind 2 weeks you didn't manage to make your presets error free and we don't allow presets with errors in the JOSM list. I don't want to invest more time here.

![screenshot](https://user-images.githubusercontent.com/7115609/81965516-6f5d7a00-9618-11ea-8abf-bff6cadf8d9a.png)

**Comment by Sowa1980** [comment]
Скачайте этот архив по ссылке https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip
добавьте его локально и убедитесь сами, все иконки загружаются и ссылки все верно указаны и прошу в преть не удалять пресеты со страницы загрузки или хотя бы проверьте перед этим.
Архив идентичен моему локальному архиву с заготовкой, скрины смотрите тоже выложил все грузится прекрасно!!
https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_window_skrin_RU.png
https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_menu_skrin.png
https://github.com/Sowa1980/Start_Data_preset/blob/master/preset_menu_skrin.png

**Comment by Klumbumbus** [comment]
Now this one is correct: https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip
But thats not what you added to https://josm.openstreetmap.de/wiki/PresetsSource. There you added https://github.com/Sowa1980/Start_Data_preset/archive/master.zip which is very different. Compare the two!

So the correct URL to add for the correct zip is: https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip

**Comment by Sowa1980** [comment]
Простите Вы не могли бы объяснить , если не трудно, откуда Вы берете эту ссылку,  в таком формате, я не понимаю и не нахожу ее у себя ее на странице в github https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip 
С этой ссылкой которая ниже понятно, она берется из адресной строки архива https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip.
И еще раз если можно поясните сейчас я должен на этой странице https://josm.openstreetmap.de/wiki/PresetsSource.
Если я Вас правильно понял удалить эту ссылку ссылку
https://github.com/Sowa1980/Start_Data_preset/archive/master.zip 
И заменить ее на эту на данной странице этой https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip
Правильно ли я Вас понял?
Если вам не трудно можете сделать снимок экрана, где мне брать ссылки в таком формате (https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip)?
Максимально похожая ссылка которую мне удалось найти на моей странице в github это вот такого вида.
https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip?raw=true
Простите за такое большое количество вопросов но я только учусь делать заготовки и осваиваю github .

**Comment by Klumbumbus** [comment]
>И еще раз если можно поясните сейчас я должен на этой странице https://josm.openstreetmap.de/wiki/PresetsSource.
Если я Вас правильно понял удалить эту ссылку ссылку
https://github.com/Sowa1980/Start_Data_preset/archive/master.zip
И заменить ее на эту на данной странице этой https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip
Правильно ли я Вас понял?

Yes.

While the URL https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip ends with ".zip" it is not a zip file, but a github page (html). So the link "View raw" on this page leads to https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip?raw=true which in the end redirects to https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip.

If you enabe the java console and add a preset with this URL https://github.com/Sowa1980/Start_Data_preset/blob/master/Start_Data_preset.zip?raw=true you can see in the console that it redirects to https://raw.githubusercontent.com/Sowa1980/Start_Data_preset/master/Start_Data_preset.zip.

**Comment by Sowa1980** [comment]
Большое спасибо за объяснение и Ваше терпение , буду пробовать и разбираться, сейчас скачаю.

**Comment by Klumbumbus** [comment]
Thanks, works now.
